# Generated by Django 4.2.2 on 2023-08-26 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("devel", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="certification",
            name="classname",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
